<exp_balanceada> ::= ""
                  | <par_balanceada> <exp_balanceada>
                  | <cor_balanceada> <exp_balanceada>
                  | <lla_balanceada> <exp_balanceada>
                  | <caracter_comun> <exp_balanceada>
<caracter_comun>  ::= cualquier carácter excepto '(', ')', '[', ']', '{', '}'
<par_balanceada>  ::= '(' <exp_balanceada> ')'
<cor_balanceada>  ::= '[' <exp_balanceada> ']'
<lla_balanceada>  ::= '{' <exp_balanceada> '}'
